version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: waah
      POSTGRES_PASSWORD: waah
      POSTGRES_DB: waah
    ports: ["5432:5432"]
    volumes: [ dbdata:/var/lib/postgresql/data ]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U waah"]
      interval: 5s
      timeout: 5s
      retries: 20
  adminer:
    image: adminer
    ports: ["8080:8080"]
    depends_on: [db]
  api:
    build: .
    env_file: .env
    ports: ["8000:8000"]
    depends_on: [db]
volumes:
  dbdata: {}